name: Deploy page

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest 
    permissions:
      contents: read
      pages: write

    steps:
    - uses: actions/checkout@v4
    - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

